// Command gendef reads the export table of a Windows PE file and writes a
// module-definition file whose every entry is a forwarder to a renamed copy of
// that same binary. It is how the drop-in shims in shim/ stay complete: the
// export list is generated from the real game files, never hand-written.
//
//	gendef -in libhl.dll -target libhl_o -out libhl.def [-skip a,b] [-list]
//
// The -skip names are left out of the forwarder list: the shim implements them
// itself.
//
// A proxy DLL that ships under the SAME name as the system DLL it stands in for
// (e.g. our winmm.dll in front of System32\winmm.dll) cannot use PE forwarder
// strings: a forwarder may not name the module it lives in, and self-naming
// recurses. The -stubs mode instead emits a C file of per-export tail-call
// thunks that jump through a pointer table the proxy fills with GetProcAddress
// at load, plus a matching .def that exports each name (at its real ordinal) as
// an alias of the generated thunk:
//
//	gendef -in winmm.dll -library winmm.dll -stubs winmm_stubs.c -out winmm.def
package main

import (
	"bytes"
	"debug/pe"
	"encoding/binary"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gendef:", err)
		os.Exit(1)
	}
}

func run() error {
	in := flag.String("in", "", "path to the original PE file to read exports from")
	target := flag.String("target", "", "module name the exports are forwarded to, without extension (e.g. libhl_o)")
	out := flag.String("out", "", "path of the .def file to write (default: stdout)")
	library := flag.String("library", "", "LIBRARY name to emit (default: base name of -in)")
	skip := flag.String("skip", "", "comma separated export names the shim implements itself")
	stubs := flag.String("stubs", "", "path of the C thunk file to write; switches to self-forwarding proxy mode")
	list := flag.Bool("list", false, "print the export names only, one per line")
	flag.Parse()

	if *in == "" {
		return fmt.Errorf("-in is required")
	}
	exports, err := readExports(*in)
	if err != nil {
		return err
	}
	if len(exports) == 0 {
		return fmt.Errorf("%s: no named exports", *in)
	}

	if *list {
		return write(*out, listing(exports))
	}

	name := *library
	if name == "" {
		name = baseName(*in)
	}

	// Self-forwarding proxy mode: emit C thunks + an aliasing .def, no -target.
	if *stubs != "" {
		skipSet := splitNames(*skip)
		for _, e := range exports {
			if skipSet[e.Name] {
				continue
			}
			if !isCIdent(e.Name) {
				return fmt.Errorf("export %q is not a valid C identifier; cannot generate a stub", e.Name)
			}
		}
		if err := write(*stubs, stubFile(exports, skipSet)); err != nil {
			return err
		}
		return write(*out, aliasDef(name, exports, skipSet))
	}

	if *target == "" {
		return fmt.Errorf("-target is required")
	}
	return write(*out, def(name, *target, exports, splitNames(*skip)))
}

// isCIdent reports whether s is a valid C identifier, so a per-export thunk can
// be named after it.
func isCIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		ok := r == '_' || (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (i > 0 && r >= '0' && r <= '9')
		if !ok {
			return false
		}
	}
	return true
}

// stubFile renders the C thunk file for the proxy DLL. Each forwarded export
// becomes a naked function that tail-jumps through mpp_<name>, a pointer the
// proxy fills at load. The mp_exports table lets the proxy resolve every slot
// from the real system DLL with GetProcAddress. Skipped names are the proxy's
// own hooked functions and get neither a slot nor a thunk here. No Windows
// headers are included on purpose: this file must not pick up the real export
// prototypes and clash with them.
func stubFile(exports []export, skip map[string]bool) string {
	var b strings.Builder
	fmt.Fprintf(&b, "/* generated by tools/gendef - do not edit */\n")
	fmt.Fprintf(&b, "/* per-export tail-call thunks for the winmm proxy; jump through pointers */\n")
	fmt.Fprintf(&b, "/* the proxy fills from System32\\winmm.dll at load. */\n\n")
	fmt.Fprintf(&b, "struct mp_export { const char *name; void **slot; };\n\n")
	for _, e := range exports {
		if skip[e.Name] {
			continue
		}
		fmt.Fprintf(&b, "void *mpp_%s;\n", e.Name)
		fmt.Fprintf(&b, "__attribute__((naked)) void mp_%s(void){ __asm__(\"jmp *mpp_%s(%%rip)\"); }\n", e.Name, e.Name)
	}
	fmt.Fprintf(&b, "\nconst struct mp_export mp_exports[] = {\n")
	n := 0
	for _, e := range exports {
		if skip[e.Name] {
			continue
		}
		fmt.Fprintf(&b, "\t{\"%s\", &mpp_%s},\n", e.Name, e.Name)
		n++
	}
	fmt.Fprintf(&b, "};\n")
	fmt.Fprintf(&b, "const unsigned mp_exports_count = %d;\n", n)
	return b.String()
}

// aliasDef renders the .def for the proxy: every forwarded name is exported at
// its real ordinal as an alias of the generated thunk (name = mp_name @ord).
// Skipped names are not exported at all; the proxy reaches them by hooking.
func aliasDef(library string, exports []export, skip map[string]bool) string {
	var b strings.Builder
	fmt.Fprintf(&b, "; generated by tools/gendef - do not edit\n")
	fmt.Fprintf(&b, "LIBRARY %s\n", library)
	fmt.Fprintf(&b, "EXPORTS\n")
	for _, e := range exports {
		if skip[e.Name] {
			continue
		}
		fmt.Fprintf(&b, "    %s = mp_%s @%d\n", e.Name, e.Name, e.Ordinal)
	}
	return b.String()
}

// export is one named entry of a PE export directory.
type export struct {
	Name    string
	Ordinal uint32
}

// readExports returns the named exports of a PE file, sorted by ordinal.
//
// debug/pe exposes no export-directory reader, so the IMAGE_EXPORT_DIRECTORY at
// data directory 0 is walked by hand.
func readExports(path string) ([]export, error) {
	f, err := pe.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close() //nolint:errcheck // opened read-only

	var dir pe.DataDirectory
	switch oh := f.OptionalHeader.(type) {
	case *pe.OptionalHeader64:
		dir = oh.DataDirectory[pe.IMAGE_DIRECTORY_ENTRY_EXPORT]
	case *pe.OptionalHeader32:
		dir = oh.DataDirectory[pe.IMAGE_DIRECTORY_ENTRY_EXPORT]
	default:
		return nil, fmt.Errorf("%s: no optional header", path)
	}
	if dir.VirtualAddress == 0 || dir.Size == 0 {
		return nil, fmt.Errorf("%s: no export directory", path)
	}

	m, err := newImage(f)
	if err != nil {
		return nil, err
	}
	base, err := m.u32(dir.VirtualAddress + 16)
	if err != nil {
		return nil, err
	}
	nameCount, err := m.u32(dir.VirtualAddress + 24)
	if err != nil {
		return nil, err
	}
	namesRVA, err := m.u32(dir.VirtualAddress + 32)
	if err != nil {
		return nil, err
	}
	ordsRVA, err := m.u32(dir.VirtualAddress + 36)
	if err != nil {
		return nil, err
	}

	out := make([]export, 0, nameCount)
	for i := uint32(0); i < nameCount; i++ {
		nameRVA, err := m.u32(namesRVA + i*4)
		if err != nil {
			return nil, err
		}
		name, err := m.cstring(nameRVA)
		if err != nil {
			return nil, err
		}
		ord, err := m.u16(ordsRVA + i*2)
		if err != nil {
			return nil, err
		}
		out = append(out, export{Name: name, Ordinal: base + uint32(ord)})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Ordinal < out[j].Ordinal })
	return out, nil
}

// image resolves relative virtual addresses against the section raw data.
type image struct{ sections []*pe.Section }

func newImage(f *pe.File) (*image, error) {
	if len(f.Sections) == 0 {
		return nil, fmt.Errorf("no sections")
	}
	return &image{sections: f.Sections}, nil
}

// at returns the section bytes starting at rva.
func (m *image) at(rva uint32) ([]byte, error) {
	for _, s := range m.sections {
		if rva < s.VirtualAddress || rva >= s.VirtualAddress+s.VirtualSize {
			continue
		}
		off := rva - s.VirtualAddress
		data, err := s.Data()
		if err != nil {
			return nil, err
		}
		if off >= uint32(len(data)) {
			return nil, fmt.Errorf("rva %#x past raw data of %s", rva, s.Name)
		}
		return data[off:], nil
	}
	return nil, fmt.Errorf("rva %#x is in no section", rva)
}

func (m *image) u32(rva uint32) (uint32, error) {
	b, err := m.at(rva)
	if err != nil || len(b) < 4 {
		return 0, orShort(err, rva)
	}
	return binary.LittleEndian.Uint32(b), nil
}

func (m *image) u16(rva uint32) (uint16, error) {
	b, err := m.at(rva)
	if err != nil || len(b) < 2 {
		return 0, orShort(err, rva)
	}
	return binary.LittleEndian.Uint16(b), nil
}

func (m *image) cstring(rva uint32) (string, error) {
	b, err := m.at(rva)
	if err != nil {
		return "", err
	}
	i := bytes.IndexByte(b, 0)
	if i < 0 {
		return "", fmt.Errorf("unterminated string at rva %#x", rva)
	}
	return string(b[:i]), nil
}

func orShort(err error, rva uint32) error {
	if err != nil {
		return err
	}
	return fmt.Errorf("truncated read at rva %#x", rva)
}

// def renders the module-definition file. Ordinals are pinned so that the shim
// is export-compatible with the original even for ordinal imports.
func def(library, target string, exports []export, skip map[string]bool) string {
	var b strings.Builder
	fmt.Fprintf(&b, "; generated by tools/gendef - do not edit\n")
	fmt.Fprintf(&b, "LIBRARY %s\n", library)
	fmt.Fprintf(&b, "EXPORTS\n")
	for _, e := range exports {
		if skip[e.Name] {
			fmt.Fprintf(&b, "    %s @%d\n", e.Name, e.Ordinal)
			continue
		}
		fmt.Fprintf(&b, "    %s = %s.%s @%d\n", e.Name, target, e.Name, e.Ordinal)
	}
	return b.String()
}

func listing(exports []export) string {
	var b strings.Builder
	for _, e := range exports {
		fmt.Fprintf(&b, "%d\t%s\n", e.Ordinal, e.Name)
	}
	return b.String()
}

func write(path, text string) error {
	if path == "" {
		_, err := os.Stdout.WriteString(text)
		return err
	}
	return os.WriteFile(path, []byte(text), 0o644)
}

func splitNames(s string) map[string]bool {
	m := map[string]bool{}
	for _, p := range strings.Split(s, ",") {
		if p = strings.TrimSpace(p); p != "" {
			m[p] = true
		}
	}
	return m
}

func baseName(path string) string {
	path = strings.ReplaceAll(path, "\\", "/")
	if i := strings.LastIndex(path, "/"); i >= 0 {
		path = path[i+1:]
	}
	return path
}
